#! /bin/bash

. ./bsd.conf

cat ./logo.txt || exit 0

while true
do
	a="`cat ./HWDP.conf | shuf | head -1`"
	b="`seq 0 255 | shuf | head -1`"
	c="`seq 0 255 | shuf | head -1`"
	torify ./torportscan $a $b $c
done
